name = "cendralingo"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
TURSO_CONNECTION_URL = "https://cendralingo-muhik.aws-ap-northeast-1.turso.io"
NEXT_PUBLIC_APP_URL = "https://cendralingo.my.id"
