name = "cendralingo"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
TURSO_CONNECTION_URL = "https://cendralingo-muhik.aws-ap-northeast-1.turso.io"
TURSO_AUTH_TOKEN = "ADD_IN_CLOUDFLARE_DASHBOARD"
NEXT_PUBLIC_APP_URL = "https://cendralingo.my.id"
MIDTRANS_SERVER_KEY = "ADD_IN_CLOUDFLARE_DASHBOARD"
MIDTRANS_CLIENT_KEY = "ADD_IN_CLOUDFLARE_DASHBOARD"
